name: Slack webhooks push notification
on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification on SUCCESS
        if: success()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "🎉 Commit Message:",
                    "value": "${{ github.event.head_commit.message }}"
                  },
                  {
                    "title": "🔎 Ref:",
                    "value": "${{ github.ref }}",
                    "short": true
                  },
                  {
                    "title": "🖥️ Compare URL",
                    "value": "${{ github.event.compare }}"
                  }
                ]
              }
            ]
